### ISSUE TITLE
AnimateDiff Error

### ISSUE THREAD

**Issue by stavrosdidakis** [eps696/SDfu#8]
Trying to run the animatediff example but I get this error. I tried less frames, but no difference.
FYI, AnimateDiff with SD and ComfyUI works fine in my computer, not sure why this is crashing.
Thanks

E:\SDFU>python src/anima.py -t "fiery dragon in a China shop" -m 15drm --frames 10 --loop
[                                                  ] 0/23
Start...
Traceback (most recent call last):
  File "E:\SDFU\src\anima.py", line 128, in <module>
    main()
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\SDFU\src\anima.py", line 118, in main
    video = sd.generate(z_, cs_frames, uc_frames, **gendict).squeeze(0) # [c,f,h,w]
  File "E:\SDFU\src\core\sdsetup.py", line 489, in generate
    noise_pred = calc_noise(lat_in, t, conds, ukwargs)
  File "E:\SDFU\src\core\sdsetup.py", line 427, in calc_noise
    noises = self.unet(x, t, conds, **ukwargs).sample.chunk(bs) # pred noise residual at step t
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\SDFU\src\core\unet_motion_model.py", line 58, in animdiff_forward
    sample, res_samples = downsample_block(hidden_states=sample, temb=emb, encoder_hidden_states=encoder_hidden_states, attention_mask=attention_mask,
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\diffusers\models\unets\unet_3d_blocks.py", line 1228, in forward
    hidden_states = motion_module(
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\diffusers\models\transformers\transformer_temporal.py", line 176, in forward
    hidden_states = block(
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\diffusers\models\attention.py", line 329, in forward
    attn_output = self.attn1(
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\diffusers\models\attention_processor.py", line 522, in forward
    return self.processor(
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\diffusers\models\attention_processor.py", line 1191, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\xformers\ops\fmha\__init__.py", line 247, in memory_efficient_attention
    return _memory_efficient_attention(
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\xformers\ops\fmha\__init__.py", line 365, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\xformers\ops\fmha\__init__.py", line 385, in _memory_efficient_attention_forward
    out, *_ = op.apply(inp, needs_gradient=False)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\xformers\ops\fmha\cutlass.py", line 202, in apply
    return cls.apply_bmhk(inp, needs_gradient=needs_gradient)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\xformers\ops\fmha\cutlass.py", line 266, in apply_bmhk
    out, lse, rng_seed, rng_offset = cls.OPERATOR(
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by eps696** [comment]
looks like a compatibility issue between diffusers and xformers (and maybe something else in the pytorch modules).
please ensure that you've got the latest diffusers version. if the problem persists, try installing another xformers version (compatible with the installed pytorch).
e.g. my setup is: 
cuda 11.8, python 3.9 (3.10 should also work), pytorch 2.0.1+cu118, torchvision 0.15.2+cu118, xformers 0.0.20.

**Comment by stavrosdidakis** [comment]
I followed the recommended installation models and it worked! Many thanks @eps696
